### ISSUE TITLE
Example running failed

### ISSUE THREAD

**Issue by darionyaphet** [wenweihu86/raft-java#20]
运行 `./bin/run_client.sh "list://127.0.0.1:8051,127.0.0.1:8052,127.0.0.1:8053" hello world` 的时候报了个错 ~  请大神看下

```
com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: serviceInterface must not be set repeatedly, please use another RpcClient
	at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:267) [brpc-java-2.5.2.jar:?]
	at com.github.wenweihu86.raft.example.server.service.ExampleService$$EnhancerByCGLIB$$c1bbc38a.set(<generated>) [raft-java-example-1.9.0.jar:?]
	at com.github.wenweihu86.raft.example.client.ClientMain.main(ClientMain.java:36) [raft-java-example-1.9.0.jar:?]
Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: serviceInterface must not be set repeatedly, please use another RpcClient
	at com.baidu.brpc.client.RpcFuture.get(RpcFuture.java:165) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.LoadBalanceInterceptor.rpcCore(LoadBalanceInterceptor.java:91) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.LoadBalanceInterceptor.invokeRpc(LoadBalanceInterceptor.java:74) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.LoadBalanceInterceptor.aroundProcess(LoadBalanceInterceptor.java:53) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.AbstractInterceptor.aroundProcess(AbstractInterceptor.java:35) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.ClientTraceInterceptor.aroundProcess(ClientTraceInterceptor.java:40) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:265) ~[brpc-java-2.5.2.jar:?]
	... 2 more
Caused by: com.baidu.brpc.exceptions.RpcException: serviceInterface must not be set repeatedly, please use another RpcClient
	at com.baidu.brpc.protocol.standard.BaiduRpcProtocol.decodeResponse(BaiduRpcProtocol.java:162) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.protocol.standard.BaiduRpcProtocol.decodeResponse(BaiduRpcProtocol.java:70) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.client.handler.ClientWorkTask.run(ClientWorkTask.java:65) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.utils.ThreadPool.consume(ThreadPool.java:131) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.utils.ThreadPool.access$000(ThreadPool.java:37) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.utils.ThreadPool$1.run(ThreadPool.java:79) ~[brpc-java-2.5.2.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201]
```

**Comment by wenweihu86** [comment]
@darionyaphet 这个错误的意思是 RpcClient只能被一个接口代理使用。看了下example代码，没这个问题把。你是自己写的example吗？

**Comment by darionyaphet** [comment]
没 我是运行`example` 里面的

**Comment by darionyaphet** [comment]
不知道为啥 现在可以了 谢谢啦

**Comment by shudo1219** [comment]
我也遇到了这个问题，
