### ISSUE TITLE
bprc exception

### ISSUE THREAD

**Issue by shudo1219** [wenweihu86/raft-java#23]
运行 ConcurrentClientMain 或者 ClientMain时，经常出现这类brpc错误：
对brpc不熟悉，有没有能避免这个问题出现的设置？

et request, key=0cea5af5-7ec6-4948-92d4-7a5f71a1b4ed, value=62b6286e-92cc-4f81-b2a7-a4312714d747, response={"success": true}, elapseMS=4
get request, key=0cea5af5-7ec6-4948-92d4-7a5f71a1b4ed, response={"value": "62b6286e-92cc-4f81-b2a7-a4312714d747"}, elapseMS=2
2019-12-17 15:55:45,742 ERROR [pool-3-thread-3]	exception :
com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: serviceInterface must not be set repeatedly, please use another RpcClient
	at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:267) [brpc-java-2.5.2.jar:?]
	at com.github.wenweihu86.raft.example.server.service.ExampleService$$EnhancerByCGLIB$$c1bbc38a.set(<generated>) [classes/:?]
	at com.github.wenweihu86.raft.example.client.ConcurrentClientMain$SetTask.run(ConcurrentClientMain.java:57) [classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: serviceInterface must not be set repeatedly, please use another RpcClient
	at com.baidu.brpc.client.RpcFuture.get(RpcFuture.java:165) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.LoadBalanceInterceptor.rpcCore(LoadBalanceInterceptor.java:91) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.LoadBalanceInterceptor.invokeRpc(LoadBalanceInterceptor.java:74) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.LoadBalanceInterceptor.aroundProcess(LoadBalanceInterceptor.java:53) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.AbstractInterceptor.aroundProcess(AbstractInterceptor.java:35) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.ClientTraceInterceptor.aroundProcess(ClientTraceInterceptor.java:40) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:265) ~[brpc-java-2.5.2.jar:?]
	... 7 more
Caused by: com.baidu.brpc.exceptions.RpcException: serviceInterface must not be set repeatedly, please use another RpcClient
	at com.baidu.brpc.protocol.standard.BaiduRpcProtocol.decodeResponse(BaiduRpcProtocol.java:162) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.protocol.standard.BaiduRpcProtocol.decodeResponse(BaiduRpcProtocol.java:70) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.client.handler.ClientWorkTask.run(ClientWorkTask.java:65) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.utils.ThreadPool.consume(ThreadPool.java:131) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.utils.ThreadPool.access$000(ThreadPool.java:37) ~[brpc-java-2.5.2.jar:?]
	at com.baidu.brpc.utils.ThreadPool$1.run(ThreadPool.java:79) ~[brpc-java-2.5.2.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
	... 1 more

**Comment by wenweihu86** [comment]
这个错误的意思是，一个RpcClient实例被多个interface使用。

**Comment by wenweihu86** [comment]
fixed by the commit:
https://github.com/wenweihu86/raft-java/commit/6686c863a25b9eaeb707e6eb61e2cea020f96504
