### ISSUE TITLE
I have one 8051 server, why I see channel is non active

### ISSUE THREAD

**Issue by gwnet** [wenweihu86/raft-java#26]
... 2 more
Exception in thread "main" com.baidu.brpc.exceptions.RpcException: com.baidu.brpc.exceptions.RpcException: channel is non active, retry another channel
	at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:276)
	at com.github.wenweihu86.raft.example.server.service.ExampleService$$EnhancerByCGLIB$$c1bbc38a.set(<generated>)
	at com.github.wenweihu86.raft.example.client.ClientMain.main(ClientMain.java:36)
Caused by: com.baidu.brpc.exceptions.RpcException: channel is non active, retry another channel
	at com.baidu.brpc.client.RpcClient.selectChannel(RpcClient.java:341)
	at com.baidu.brpc.interceptor.LoadBalanceInterceptor.selectChannel(LoadBalanceInterceptor.java:79)
	at com.baidu.brpc.interceptor.LoadBalanceInterceptor.invokeRpc(LoadBalanceInterceptor.java:73)
	at com.baidu.brpc.interceptor.LoadBalanceInterceptor.aroundProcess(LoadBalanceInterceptor.java:53)
	at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
	at com.baidu.brpc.interceptor.AbstractInterceptor.aroundProcess(AbstractInterceptor.java:35)
	at com.baidu.brpc.interceptor.ClientTraceInterceptor.aroundProcess(ClientTraceInterceptor.java:40)
	at com.baidu.brpc.interceptor.DefaultInterceptorChain.intercept(DefaultInterceptorChain.java:43)
	at com.baidu.brpc.client.BrpcProxy.intercept(BrpcProxy.java:265)
	... 2 more
Disconnected from the target VM, address: '127.0.0.1:54667', transport: 'socket'

**Comment by wenweihu86** [comment]
@gwnet 这里是brpc-java负载均衡没有及时把重试过的实例剔除掉。后续会优化。
